### ISSUE TITLE
User can search the name of a city.

### ISSUE THREAD

**Issue by brandonechin** [brandonechin/Weather-Forecast#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search the name of a city that they want to know the forecast of.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a text box that allows users to search for the name of a city.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/111926994/211870433-11842f24-bc0b-41b1-a17d-181793d4f815.png) ![image](https://user-images.githubusercontent.com/111926994/211870525-a9c5df1c-35d8-4d95-ac80-d2c9b941d2fd.png)
![image](https://user-images.githubusercontent.com/111926994/211870879-be3e9249-3821-424d-9e3d-1bfa6297053c.png) ![image](https://user-images.githubusercontent.com/111926994/211870994-6f8372fe-23cf-4a2f-a2c0-fba471610a64.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create an HTML skeleton.
  - [x] Add  `<meta>`  tags for responsive layouts. 
- [x] Create a `<input>` for text and `<button>` that can be clicked.
  - [x] Make sure that click targets are either `<a>` or `<button>` elements.
  - [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
  - [x] Add a hamburger menu to the nav bar for mobile viewing and an anchor for desktop viewing as depicted in the wireframes. 
- [x] Complete the HTML search box using the appropriate responsive layout classes.
  - [x] Write CSS for mobile devices first.
  - [x] Adjust styling to fluidly adapt to desktop.
- [x] Make the search input `required` .
- [x] Add a `submit` event listener to the button element that:
  - [x]  stores the textbox input values in a new object.
  - [x] assigns an `entryId` property to the new object, taken from the `nextEntryId` property of the data model.
  - [x] increments the `nextEntryId` property of the data model so that if another entry is submitted later, it will receive a different `entryId`.
  - [x] adds the new object to the beginning of the data model's array of cities.
- [x] In `data.js`, add a `beforeunload` event listener to the `window` object that serializes the data model as JSON and stores the JSON in `localStorage`.
- [x]  At the bottom of `data.js`, include a conditional statement that:
  - [x] checks to see if there is a JSON data model stored in `localStorage`.
  - [x] if there is, parse it and assign it to the initial `data` variable so that the user can continue adding entries to the pre-existing data model.
- [x]  Test the app by submitting some new entries and then reloading the page to confirm that:
  - [x]  the data model is being saved to `localStorage` before each page reload.
  - [x]  each new journal entry object is receiving an incrementing `entryId` property.
- [x] Create `submit` add event listener which submits XML requests, returns data and stores it in the data model.
  - [x] add city info property and city forecast property to the data model to store requested data.
  - [x] create a function, that listens to the submit event, and successfully retrieves the input city's data.
  - [x] create a function that retrieves the input city's forecast data using the city's data and call the function in the previous functions load event handler.
  - [x] check the data model to confirm if the data is being retrieved successfully.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
