### ISSUE TITLE
User can see the current forecast of the city.

### ISSUE THREAD

**Issue by brandonechin** [brandonechin/Weather-Forecast#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the current forecast of the city using the OpenWeather API.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User will be able to see the forecast of the city they searched.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/111926994/211898970-6d8f95ce-dce3-44f4-9ff7-6f18c9bbcafb.png)
![image](https://user-images.githubusercontent.com/111926994/211899239-c60c1ee9-1e51-481b-bd4b-20bfed63b378.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add an empty unordered list to the `div[id="city-page"]` element in HTML. 
- [x] Create a dummy city forecast to the unordered list in the HTML and style them to match the example wireframes.
- [x] Check that the example city forecast created in the unordered list are responsive for both mobile and desktop screens.
- [x] Within the load event handler of the function that retrieves the weather data for a city, change the text content of the dummy city forecast in the HTML file using `this.response` data.
- [x] Create a new function named viewSwap with a single parameter representing the name of the view to show (the value will be either ”search-page”, ”city-page”, or "favorites-page"). This function should show the view whose name was provided as an argument, as well as assign the string argument to the `data.view` property so that the currently shown view is tracked in the data model for the application.
- [x] Create a modal that activates when the `hamburger` icon is clicked.
  - [x] it should have an anchor for `New Search` and `Favorites`
  - [x] An add event listener should unhide the modal.
- [x] Add an anchor `New Search` to the navbar in the desktop-view on the city-page to show the `"search-page"` view. 
- [x] Create  an add event listener to the `New Search` button on the `"city-page"`  and to the `New Search` button on the modal that changes the view back to the `"search-page"`
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
