### ISSUE TITLE
User can add a city and view on favorites list.

### ISSUE THREAD

**Issue by brandonechin** [brandonechin/Weather-Forecast#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can add the city to a favorites list by clicking on the heart icon.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can add the city to their favorites list by clicking on the blue heart icon. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="158" alt="image" src="https://user-images.githubusercontent.com/111926994/212191306-b308115a-934c-4a76-ba1a-a4aaae3cee98.png"><img width="158" alt="image" src="https://user-images.githubusercontent.com/111926994/212191143-0e46fbac-1712-42d4-885d-dc71f290923c.png">

<img width="209" alt="image" src="https://user-images.githubusercontent.com/111926994/212165488-81b52196-bf67-4df5-b1d5-885b510d2b2b.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add an empty unordered list to the  `div[id="favorites-page"]`  element in the HTML.
- [x] Copy over the dummy forecast, from the previous issue, to the unordered list in HTML. In this dummy forecast, add a trashbin icon as depicted in the wireframe.
- [x] Define a function named `renderCity` with a single parameter named `city`. This parameter represents a single object for a single city entry from the `data.forecast` array. The function should generate and return a DOM tree for a single city that matches the city you created in the unordered list.
- [x] Create a `click` event listener that renders the city when the heart Icon is clicked. 
  - [x] In the event handler (callback function), use the `new` operator for an `XMLHttpRequest` to retrieve the city forecast data.
  - [x] In the event handler of the `load` event listener, render the city's forecast.
    - [x] If the city has already been added to the favorites list, do not render the city's forecast. 
- [x] Prepend the city to the unordered list in the `div[id="favorites-page"]` 
- [x] Create a `click` event listener that changes the page to the favorites list.
  - [x] Do so for both desktop and mobile views. 
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
