### ISSUE TITLE
User can view the current forecasts for cities in favorites list.

### ISSUE THREAD

**Issue by brandonechin** [brandonechin/Weather-Forecast#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view their favorites list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can view their favorites list by clicking on the favorites button.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="141" alt="image" src="https://user-images.githubusercontent.com/111926994/212188937-7f0dc085-ac74-4cb3-b599-b24a79772f26.png"><img width="141" alt="image" src="https://user-images.githubusercontent.com/111926994/212189075-7b716514-1ff7-4413-af57-413679d91180.png"><img width="141" alt="image" src="https://user-images.githubusercontent.com/111926994/212188721-c9e6ca18-62b0-432d-9683-0018b7048f97.png">
<img width="212" alt="image" src="https://user-images.githubusercontent.com/111926994/212189606-c4a5d7c0-fc77-4917-87e7-ef5c17ff1140.png"> <img width="212" alt="image" src="https://user-images.githubusercontent.com/111926994/212189659-6391f9d7-550c-4e5d-b4fc-daf233d0e2cb.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make the favorites list responsive to both mobile and desktop views.
- [x] Create a `click` add event listener that updates the favorites page when the user clicks on one of the favorites anchors.
  - [x] In the event handler for the click event, define a function that requests the forecast data from the API
  - [x] Update the forecasts only if they are added to `data.favorites`.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
