### ISSUE TITLE
User can delete a city from their favorite list.

### ISSUE THREAD

**Issue by brandonechin** [brandonechin/Weather-Forecast#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete city from favorites list. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can delete a city from their favorites list by clicking on the trach bin icon.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/111926994/212190052-fa401fb8-a7ab-4608-ab61-bd8739cbeb41.png">
<img width="578" alt="image" src="https://user-images.githubusercontent.com/111926994/212190218-9605b660-9910-494f-a876-c0b400e859e1.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a `click` add event listener to show a modal confirmation when the user clicks on the trash bin icon.
- [x] When the user clicks **NO**, hide the modal.
- [x] When the user clicks **YES**:
  - [x] Remove the city's forecast `li` element from the favorites list.
  - [x] Hide the modal.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
